### ISSUE TITLE
Multiple same forms on one page 

### ISSUE THREAD

**Issue by barrykooij** [wpninjas/ninja-forms#931]
When you add the same form multiple times on the same page, the first form will also be submitted (even you press submit on another form).

See this recording where I fill out the second form, press submit and the first form starts processing.
![nf-forms](https://cloud.githubusercontent.com/assets/2846594/10139115/c167220c-6601-11e5-8269-f870c2895a70.gif)

Possibly related: #770

**Comment by kstover** [comment]
This is a known issue, and may be fixed in the 3.0 re-write of Ninja Forms. This has to do with how forms are referenced within the JS code. We use the form ID to target specific elements on the page. I'm going to tag this as wontfix because we know it exists, but aren't sure how to tackle it, and we don't have much development bandwidth to throw at it at the moment.

**Comment by jameslaws** [comment]
@kstover, I recommend that this be relabeled as a bug and blessed for a future release instead of won't fix. Seems like a common use case that we would want to tackle. Yay or Nay?

**Comment by tylerdigital** [comment]
Any word on whether this is fixed for 3.0?

**Comment by kstover** [comment]
This is a really tricky thing to tackle. I think we'll have to have a longer discussion with @kjohnson and @klhall1987 to see if we can come up with any solutions. At the moment, I'm not sure how we'd achieve it.

**Comment by msklenica** [comment]
The issue is still there in latest 3.x release.
I would suggest adding unique IDs to physical part of the code (HTML) and have a shared javascript code to operate the submission and validation (considering that same 2 forms have same configuration, label texts, etc.).

**Comment by kjohnson** [comment]
We are working on some refactoring that should resolve this.

**Comment by johannesmutter** [comment]
Also have this problem:
I have a contact form + a simple newsletter subscription form. Users can send the newsletter form because the contact form get’s validated, too.

**Comment by klhall1987** [comment]
reported again by [Fred](https://wpninjas.kustomerapp.com/app/customers/588cad077f667f1100f75e0e/event/588cad0851b4d01000ed2cc8)

**Comment by andrewfleming** [comment]
I see this is tagged as major bug, but thought it worth mentioning that with version 3.0.27 multiple forms on a single page now results in the first form loading, and subsequent forms displaying the spinner.

**Comment by kstover** [comment]
Multiple DIFFERENT forms on the same page should work properly. Multiple copies of the SAME FORM are still an issue that we're working on. We have another issue open for that, so I'm going to close this one. If multiple different forms on the same page is still causing a problem on your site, feel free to open a support ticket at ninjaforms.com and we'll take a look at your install.

**Comment by isleshocky77** [comment]
@kstover Care to reference the other issue which is opened for multiple of the same form on a single page? This was the first result for my google for the bug.

**Comment by mynameiskyle** [comment]
Another vote to mark this Open. 

My use-case is we have a Newsletter form in the sidebar that is persistent but sometimes we want to put that same form inline as a speedbump in the article itself. As it stands now, one of those two forms will get the spinner.
